import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import SideNavBar from '@/component/SideNavBar';
import { useEffect, useState } from 'react';
import { Col, Row } from 'react-bootstrap';
import SummarySideBar from '@/component/SummarySideBar';
import MainContent from '@/component/mainComponent/MainContent';
import { useAppDispatch, useAppSelector } from '@/redux/Hooks';
import { fecthRecomended } from '@/redux/middleware/fetchRecomended';
import { fecthReadingList } from '@/redux/middleware/fetchReadingList';
import Cover from '@/component/Cover';
import OnBoarding from './boarding';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [mount, setMount] = useState(false);
  const dispatch = useAppDispatch();

  const state: any = useAppSelector((states) => states.user);

  if (state.token) {
    console.log('yes i am dispatching', state.token);

    // dispatch(fecthRecomended(state.token));
    dispatch(fecthReadingList(state.token));
  }
  useEffect(() => {}, []);
  useEffect(() => {
    setMount(true);
  });
  if (!mount) {
    return;
  }
  return (
    <>
      <Head>
        <title>Open Book</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div style={{ background: 'black' }}>
        <Cover />
        {/* <OnBoarding /> */}
      </div>
      {/* <div style={{ background: 'black' }}>
        <Row>
          <Col style={{ padding: '0px' }} md={3}>
            <SideNavBar />
          </Col>
          <Col style={{ padding: '0px' }} md={6}>
            <MainContent />
          </Col>
          <Col style={{ padding: '0px' }} md={3}>
            <SummarySideBar />
          </Col>
        </Row>
      </div> */}
      {/* <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main> */}
    </>
  );
}
